// Variantes padrão (mesma para quase todos os suplementos)
const _STD = () => [
  { titulo:"COMPRE 1 LEVE 2",  preco:14990, comparar:29990, desconto:50 },
  { titulo:"COMPRE 2 LEVE 4",  preco:26990, comparar:59990, desconto:55 },
  { titulo:"COMPRE 3 LEVE 6",  preco:35990, comparar:89990, desconto:60, popular:true },
  { titulo:"COMPRE 4 LEVE 8",  preco:44990, comparar:119990, desconto:62 },
  { titulo:"COMPRE 5 LEVE 10", preco:53990, comparar:149990, desconto:64 },
];

// tipo → define qual template de copy usa em produto.html
// "geral" | "masc" | "fem"

const PRODUTOS = [
  {
    slug:"glicofit", nome:"Glicofit", tipo:"geral",
    titulo:"Glicofit",
    subtitulo:"Suplemento natural em gotas para equilíbrio glicêmico",
    badge:"MAIS VENDIDO", badgeColor:"#15a731",
    variantes:_STD(),
    imagens:[
      "/img/produtos/glicofit/1.png",
      "/img/produtos/glicofit/2.png",
      "/img/produtos/glicofit/3.png",
      "/img/produtos/glicofit/4.png",
      "/img/produtos/glicofit/5.png",
    ],
  },
  {
    slug:"insufree", nome:"Insufree", tipo:"geral",
    titulo:"Insufree",
    subtitulo:"Fórmula natural para suporte metabólico e glicêmico",
    badge:"OFERTA DO DIA", badgeColor:"#e67e22",
    variantes:_STD(),
    imagens:[
      "/img/produtos/insufree/1.png",
      "/img/produtos/insufree/2.png",
      "/img/produtos/insufree/3.png",
      "/img/produtos/insufree/4.png",
      "/img/produtos/insufree/5.png",
    ],
  },
  {
    slug:"purenex-glico", nome:"Purenex Glico", tipo:"geral",
    titulo:"Purenex Glico",
    subtitulo:"Controle glicêmico com ingredientes da natureza",
    badge:"LANÇAMENTO", badgeColor:"#8e44ad",
    variantes:_STD(),
    imagens:[
      "/img/produtos/purenex-glico/1.png",
      "/img/produtos/purenex-glico/2.png",
      "/img/produtos/purenex-glico/3.png",
      "/img/produtos/purenex-glico/4.png",
      "/img/produtos/purenex-glico/5.png",
    ],
  },
  {
    slug:"pulmoclean", nome:"Pulmoclean", tipo:"geral",
    titulo:"Pulmoclean",
    subtitulo:"Suporte respiratório com ingredientes naturais",
    badge:"MAIS VENDIDO", badgeColor:"#15a731",
    variantes:_STD(),
    imagens:[
      "/img/produtos/pulmoclean/1.png",
      "/img/produtos/pulmoclean/2.png",
      "/img/produtos/pulmoclean/3.png",
      "/img/produtos/pulmoclean/4.png",
      "/img/produtos/pulmoclean/5.png",
      "/img/produtos/pulmoclean/6.png",
    ],
  },
  {
    slug:"dht-blocker", nome:"DHT Blocker", tipo:"masc",
    titulo:"DHT Blocker",
    subtitulo:"Bloqueador natural de DHT para saúde capilar masculina",
    badge:"OFERTA DO DIA", badgeColor:"#e67e22",
    variantes:_STD(),
    imagens:[
      "/img/produtos/dht-blocker/1.png",
      "/img/produtos/dht-blocker/2.png",
      "/img/produtos/dht-blocker/3.png",
      "/img/produtos/dht-blocker/4.png",
      "/img/produtos/dht-blocker/5.png",
    ],
  },
  {
    slug:"hair-fortin", nome:"Hair Fortin", tipo:"fem",
    titulo:"Hair Fortin",
    subtitulo:"Nutrição capilar intensiva de dentro para fora",
    badge:"OFERTA DO DIA", badgeColor:"#e67e22",
    variantes:_STD(),
    imagens:[
      "/img/produtos/hair-fortin/1.png",
      "/img/produtos/hair-fortin/2.png",
      "/img/produtos/hair-fortin/3.png",
      "/img/produtos/hair-fortin/4.png",
      "/img/produtos/hair-fortin/5.png",
    ],
  },
  {
    slug:"long-beauty", nome:"Long Beauty", tipo:"fem",
    titulo:"Long Beauty",
    subtitulo:"Beleza e vitalidade capilar com a força da natureza",
    badge:"LANÇAMENTO", badgeColor:"#c0392b",
    variantes:_STD(),
    imagens:[
      "/img/produtos/long-beauty/1.png",
      "/img/produtos/long-beauty/2.png",
      "/img/produtos/long-beauty/3.png",
      "/img/produtos/long-beauty/4.png",
      "/img/produtos/long-beauty/5.png",
    ],
  },
  {
    slug:"rosa-oriental", nome:"Rosa Oriental", tipo:"fem",
    titulo:"Rosa Oriental",
    subtitulo:"Beleza e bem-estar feminino com ervas do Oriente",
    badge:"OFERTA DO DIA", badgeColor:"#e91e8c",
    variantes:_STD(),
    imagens:[
      "/img/produtos/rosa-oriental/1.png",
      "/img/produtos/rosa-oriental/2.png",
      "/img/produtos/rosa-oriental/3.png",
      "/img/produtos/rosa-oriental/4.png",
      "/img/produtos/rosa-oriental/5.png",
    ],
  },
  {
    slug:"rejuvita", nome:"Rejuvita", tipo:"fem",
    titulo:"Rejuvita",
    subtitulo:"Antienvelhecimento e rejuvenescimento com ativos naturais",
    badge:"MAIS VENDIDO", badgeColor:"#15a731",
    variantes:_STD(),
    imagens:[
      "/img/produtos/rejuvita/1.png",
      "/img/produtos/rejuvita/2.png",
      "/img/produtos/rejuvita/3.png",
      "/img/produtos/rejuvita/4.png",
      "/img/produtos/rejuvita/5.png",
    ],
  },
  {
    slug:"meno-care", nome:"Meno Care", tipo:"fem",
    titulo:"Meno Care",
    subtitulo:"Suporte natural para os sintomas da menopausa",
    badge:"OFERTA DO DIA", badgeColor:"#e91e8c",
    variantes:_STD(),
    imagens:[
      "/img/produtos/meno-care/1.png",
      "/img/produtos/meno-care/2.png",
      "/img/produtos/meno-care/3.png",
      "/img/produtos/meno-care/4.png",
      "/img/produtos/meno-care/5.png",
    ],
  },
  {
    slug:"dura-max", nome:"DuraMax", tipo:"masc",
    titulo:"DuraMax",
    subtitulo:"Fórmula masculina para disposição e vitalidade",
    badge:"LANÇAMENTO", badgeColor:"#8e44ad",
    variantes:[
      { titulo:"1 FRASCO",         preco:10990, comparar:29990, desconto:63 },
      { titulo:"COMPRE 2 LEVE 3",  preco:19990, comparar:59990, desconto:66 },
      { titulo:"COMPRE 3 LEVE 5",  preco:35990, comparar:89990, desconto:60, popular:true },
      { titulo:"COMPRE 4 LEVE 8",  preco:44990, comparar:119990, desconto:62 },
      { titulo:"COMPRE 5 LEVE 10", preco:53990, comparar:149990, desconto:64 },
    ],
    imagens:[
      "/img/produtos/dura-max/1.png",
      "/img/produtos/dura-max/2.png",
      "/img/produtos/dura-max/3.png",
      "/img/produtos/dura-max/4.png",
      "/img/produtos/dura-max/5.png",
    ],
  },
  {
    slug:"viriforte", nome:"Viriforte", tipo:"masc",
    titulo:"Viriforte",
    subtitulo:"Força e vitalidade masculina com a natureza",
    badge:"OFERTA DO DIA", badgeColor:"#e67e22",
    variantes:_STD(),
    imagens:[
      "/img/produtos/viriforte/1.png",
      "/img/produtos/viriforte/2.png",
      "/img/produtos/viriforte/3.png",
      "/img/produtos/viriforte/4.png",
      "/img/produtos/viriforte/5.png",
    ],
  },
  {
    slug:"elefantol", nome:"Elefantol", tipo:"masc",
    titulo:"Elefantol",
    subtitulo:"Potência e resistência com ativos naturais",
    badge:"MAIS VENDIDO", badgeColor:"#15a731",
    variantes:_STD(),
    imagens:[
      "/img/produtos/elefantol/1.png",
      "/img/produtos/elefantol/2.png",
      "/img/produtos/elefantol/3.png",
      "/img/produtos/elefantol/4.png",
      "/img/produtos/elefantol/5.png",
    ],
  },
  {
    slug:"mounjax", nome:"Mounjax", tipo:"geral",
    titulo:"Mounjax",
    subtitulo:"Suporte ao emagrecimento com ingredientes naturais",
    badge:"OFERTA DO DIA", badgeColor:"#e67e22",
    variantes:_STD(),
    imagens:[
      "/img/produtos/mounjax/1.png",
      "/img/produtos/mounjax/2.png",
      "/img/produtos/mounjax/3.png",
      "/img/produtos/mounjax/4.png",
      "/img/produtos/mounjax/5.png",
    ],
  },
  {
    slug:"burnzine", nome:"Burnzine", tipo:"geral",
    titulo:"Burnzine",
    subtitulo:"Termogênico natural para acelerar o metabolismo",
    badge:"OFERTA DO DIA", badgeColor:"#c0392b",
    variantes:_STD(),
    imagens:[
      "/img/produtos/burnzine/1.png",
      "/img/produtos/burnzine/2.png",
      "/img/produtos/burnzine/3.png",
      "/img/produtos/burnzine/4.png",
      "/img/produtos/burnzine/5.png",
    ],
  },
  {
    slug:"neurovex", nome:"Neurovex", tipo:"geral",
    titulo:"Neurovex",
    subtitulo:"Suporte cognitivo e neurológico com nootrópicos naturais",
    badge:"LANÇAMENTO", badgeColor:"#8e44ad",
    variantes:_STD(),
    imagens:[
      "/img/produtos/neurovex/1.png",
      "/img/produtos/neurovex/2.png",
      "/img/produtos/neurovex/3.png",
      "/img/produtos/neurovex/4.png",
      "/img/produtos/neurovex/5.png",
    ],
  },
  {
    slug:"memoralis", nome:"Memoralis", tipo:"geral",
    titulo:"Memoralis",
    subtitulo:"Memória e concentração com nootrópicos naturais",
    badge:"OFERTA DO DIA", badgeColor:"#8e44ad",
    variantes:_STD(),
    imagens:[
      "/img/produtos/memoralis/1.png",
      "/img/produtos/memoralis/2.png",
      "/img/produtos/memoralis/3.png",
      "/img/produtos/memoralis/4.png",
      "/img/produtos/memoralis/5.png",
    ],
  },
  {
    slug:"nervomax", nome:"Nervomax", tipo:"geral",
    titulo:"Nervomax",
    subtitulo:"Saúde do sistema nervoso com ingredientes naturais",
    badge:"MAIS VENDIDO", badgeColor:"#15a731",
    variantes:_STD(),
    imagens:[
      "/img/produtos/nervomax/1.png",
      "/img/produtos/nervomax/2.png",
      "/img/produtos/nervomax/3.png",
      "/img/produtos/nervomax/4.png",
      "/img/produtos/nervomax/5.png",
    ],
  },
  {
    slug:"vision-x", nome:"Vision-X", tipo:"geral",
    titulo:"Vision-X",
    subtitulo:"Saúde ocular com luteína e zeaxantina naturais",
    badge:"OFERTA DO DIA", badgeColor:"#2980b9",
    variantes:_STD(),
    imagens:[
      "/img/produtos/vision-x/1.png",
      "/img/produtos/vision-x/2.png",
      "/img/produtos/vision-x/3.png",
      "/img/produtos/vision-x/4.png",
      "/img/produtos/vision-x/5.png",
    ],
  },
  {
    slug:"articuly", nome:"Articuly", tipo:"geral",
    titulo:"Articuly",
    subtitulo:"Articulações flexíveis com colágeno e ativos naturais",
    badge:"MAIS VENDIDO", badgeColor:"#15a731",
    variantes:_STD(),
    imagens:[
      "/img/produtos/articuly/1.png",
      "/img/produtos/articuly/2.png",
      "/img/produtos/articuly/3.png",
      "/img/produtos/articuly/4.png",
      "/img/produtos/articuly/5.png",
    ],
  },
  {
    slug:"hemo-gotas", nome:"Hemo Gotas", tipo:"geral",
    titulo:"Hemo Gotas",
    subtitulo:"Suporte ao sangue e circulação com ferro natural",
    badge:"OFERTA DO DIA", badgeColor:"#c0392b",
    variantes:_STD(),
    imagens:[
      "/img/produtos/hemo-gotas/1.png",
      "/img/produtos/hemo-gotas/2.png",
      "/img/produtos/hemo-gotas/3.png",
      "/img/produtos/hemo-gotas/4.png",
      "/img/produtos/hemo-gotas/5.png",
    ],
  },
  {
    slug:"prostavex", nome:"Prostavex", tipo:"masc",
    titulo:"Prostavex",
    subtitulo:"Saúde da próstata com saw palmetto e zinco",
    badge:"OFERTA DO DIA", badgeColor:"#2980b9",
    variantes:_STD(),
    imagens:[
      "/img/produtos/prostavex/1.png",
      "/img/produtos/prostavex/2.png",
      "/img/produtos/prostavex/3.png",
      "/img/produtos/prostavex/4.png",
      "/img/produtos/prostavex/5.png",
    ],
  },
  {
    slug:"mitocondril", nome:"Mitocondril", tipo:"geral",
    titulo:"Mitocondril",
    subtitulo:"Energia celular profunda com CoQ10 e ativos mitocondriais",
    badge:"LANÇAMENTO", badgeColor:"#8e44ad",
    variantes:_STD(),
    imagens:[
      "/img/produtos/mitocondril/1.png",
      "/img/produtos/mitocondril/2.png",
      "/img/produtos/mitocondril/3.png",
      "/img/produtos/mitocondril/4.png",
      "/img/produtos/mitocondril/5.png",
    ],
  },
  {
    slug:"akkermat", nome:"Akkermat", tipo:"geral",
    titulo:"Akkermat",
    subtitulo:"Microbiota intestinal com Akkermansia e probióticos naturais",
    badge:"LANÇAMENTO", badgeColor:"#15a731",
    variantes:_STD(),
    imagens:[
      "/img/produtos/akkermat/1.png",
      "/img/produtos/akkermat/2.png",
      "/img/produtos/akkermat/3.png",
      "/img/produtos/akkermat/4.png",
      "/img/produtos/akkermat/5.png",
    ],
  },
  {
    slug:"naturion", nome:"Naturion", tipo:"geral",
    titulo:"Naturion",
    subtitulo:"Equilíbrio mineral e vital com eletrólitos naturais",
    badge:"OFERTA DO DIA", badgeColor:"#e67e22",
    variantes:_STD(),
    imagens:[
      "/img/produtos/naturion/1.png",
      "/img/produtos/naturion/2.png",
      "/img/produtos/naturion/3.png",
      "/img/produtos/naturion/4.png",
      "/img/produtos/naturion/5.png",
    ],
  },
  {
    slug:"corretor-postural", nome:"Corretor Postural", tipo:"geral",
    titulo:"Corretor Postural — Ombro e Lombar",
    subtitulo:"Alinhamento 3 em 1 · Coluna · Ombros · Lombar",
    badge:"FRETE GRÁTIS", badgeColor:"#15a731",
    variantes:[
      { titulo:"TAMANHO ÚNICO", preco:12990, comparar:19990, desconto:35 },
    ],
    imagens:[
      "/img/produtos/corretor-postural/1.webp",
      "/img/produtos/corretor-postural/2.webp",
    ],
  },
  {
    slug:"teste", nome:"Produto Teste", tipo:"geral",
    titulo:"Produto Teste",
    subtitulo:"Produto interno para testes de pagamento",
    variantes:[
      { titulo:"TESTE R$2", preco:200, comparar:1000, desconto:80 },
    ],
    imagens:[
      "/img/produtos/glicofit/1.png",
    ],
  },
];
